apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wellenplan.fullname" . }}
  labels:
    {{- include "wellenplan.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "wellenplan.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        checksum/config: {{ .Values.env | toYaml | sha256sum }}
        checksum/secret: {{ .Values.secret | toYaml | sha256sum }}
      labels:
        {{- include "wellenplan.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "wellenplan.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "wellenplan.fullname" . }}
            {{- if .Values.secret.enabled }}
            - secretRef:
                name: {{ include "wellenplan.fullname" . }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8055
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /server/health
              port: http
          readinessProbe:
            httpGet:
              path: /server/health
              port: http
          volumeMounts:
            - name: upload-dir
              mountPath: /opt/app-root/src/uploads
          {{- if .Values.cockroachdb.enabled }}
            - name: cockroachdb-client-secret
              mountPath: /var/run/secrets/cockroachdb-client-secret
              readOnly: true
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: upload-dir
          emptyDir: {}
      {{- if .Values.cockroachdb.enabled }}
        - name: cockroachdb-client-secret
          secret:
            secretName: {{ tpl .Values.secret.db.clientSecretName . }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
