{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wellenplan.fullname" . }}
  labels:
    {{- include "wellenplan.labels" . | nindent 4 }}
type: Opaque
data:
  # database
  DB_PASSWORD: {{ .Values.secret.db.password | b64enc | quote }}
  # rate limiter
  {{- if .Values.env.rateLimiter.enabled }}
  {{- with .Values.secret.rateLimiter.password }}
  RATE_LIMITER_REDIS_PASSWORD: {{ . | b64enc | quote }}
  {{- end }}
  {{- end }}
  # cache
  {{- if .Values.env.cache.enabled }}
  {{- with .Values.secret.cache.password }}
  CACHE_REDIS_PASSWORD: {{ . | b64enc | quote }}
  {{- end }}
  {{- end }}
  # storage
  {{- with .Values.secret.storage.minio.secret }}
  STORAGE_MINIO_SECRET: {{ . | b64enc | quote }}
  {{- end }}
  # security
  SECRET: {{ default (randAlphaNum 32) .Values.secret.security.secret | b64enc | quote }}
  {{- if .Values.secret.extraSecrets }}
  {{- range $k,$v := .Values.secret.extraSecrets }}
  {{ $k }}: {{ $v | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end -}}
