name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  call-workflow:
    uses: wellenplan/actions/.github/workflows/semantic-release.yaml@v0.1.0
    secrets:
      ORGA_USER_TOKEN: ${{ secrets.ORGA_USER_TOKEN }}
